+ source ../common_lib/fsio_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ lsblk
++ grep test_vggroup
++ [[ 1 -eq 0 ]]
++ rm -rf /tmp/point120231007155656
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ grep expect
+ rpm -qa
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Sat Oct  7 15:56:57 2023 - INFO  - Start to prepare the database config.
+ point_list=($(CREATE_FS xfs))
++ CREATE_FS xfs
++ fs_type=xfs
+++ date +%Y%m%d%H%M%S
++ cur_date=20231007155657
+++ CREATE_VG
++++ date +%Y%m%d%H%M%S
+++ cur_date=20231007155657
++++ lsblk
++++ grep disk
++++ awk '{print $1}'
++++ tail -n 1
+++ free_disk=vda
+++ disk_name=/dev/vda
+++ pvcreate /dev/vda -f
+++ [[ 127 -eq 0 ]]
++++ pvcreate /dev/vda
++++ grep test_vggroup
++++ cut -d '"' -f 4
+++ vggroup=
+++ printf
printf: usage: printf [-v var] format [arguments]
++ vggroup=
++ count=1
++ msg=' '
++ for fs in ${fs_type[@]}
++ lvname=test_lv120231007155657
++ point=/tmp/point120231007155657
++ lvcreate -n test_lv120231007155657 -L 512M -y
../common_lib/fsio_lib.sh: line 107: lvcreate: command not found
++ mkfs -t xfs /dev//test_lv120231007155657
mkfs: failed to execute mkfs.xfs: No such file or directory
++ mkdir /tmp/point120231007155657
++ mount /dev//test_lv120231007155657 /tmp/point120231007155657
mount: /tmp/point120231007155657: special device /dev//test_lv120231007155657 does not exist.
       dmesg(1) may have more information after failed mount system call.
++ msg=' /tmp/point120231007155657 '
++ count=2
++ echo /tmp/point120231007155657
+ vggroup=/tmp/point120231007155657
+ xfs_point=
++ lsblk
++ grep /tmp/point120231007155657
++ awk '{print $1}'
++ cut -d - -f 2
+ lv=
+ LOG_INFO 'Finish to prepare the database config.'
+ message='Finish to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish to prepare the database config.'
Sat Oct  7 15:56:57 2023 - INFO  - Finish to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Sat Oct  7 15:56:57 2023 - INFO  - Start to run test.
++ df -i
++ grep /dev/mapper//tmp/point120231007155657-
++ awk '{print $2}'
+ size1=
+ lvextend -L +1G /dev//tmp/point120231007155657/
oe_test_FSIO_xfs_resize2fs.sh: line 33: lvextend: command not found
+ xfs_growfs /dev//tmp/point120231007155657/
oe_test_FSIO_xfs_resize2fs.sh: line 34: xfs_growfs: command not found
+ CHECK_RESULT 127 0 0 'Change size of xfs failed.'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='Change size of xfs failed.'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'Change size of xfs failed.'
+ LOG_ERROR 'Change size of xfs failed.'
+ message='Change size of xfs failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Change size of xfs failed.'
Sat Oct  7 15:56:57 2023 - ERROR - Change size of xfs failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_xfs_resize2fs.sh line 35'
+ message='oe_test_FSIO_xfs_resize2fs.sh line 35'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_xfs_resize2fs.sh line 35'
Sat Oct  7 15:56:57 2023 - ERROR - oe_test_FSIO_xfs_resize2fs.sh line 35
+ '[' 0 -eq 1 ']'
+ return 0
++ df -i
++ awk '{print $2}'
++ grep /dev/mapper//tmp/point120231007155657-
+ size2=
+ [[ '' -ne '' ]]
+ CHECK_RESULT 1 0 0 'Resize for xfs failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Resize for xfs failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Resize for xfs failed.'
+ LOG_ERROR 'Resize for xfs failed.'
+ message='Resize for xfs failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Resize for xfs failed.'
Sat Oct  7 15:56:57 2023 - ERROR - Resize for xfs failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_xfs_resize2fs.sh line 38'
+ message='oe_test_FSIO_xfs_resize2fs.sh line 38'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_xfs_resize2fs.sh line 38'
Sat Oct  7 15:56:57 2023 - ERROR - oe_test_FSIO_xfs_resize2fs.sh line 38
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Sat Oct  7 15:56:57 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Sat Oct  7 15:56:57 2023 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Sat Oct  7 15:56:57 2023 - INFO  - Start to restore the test environment.
++ echo /tmp/point120231007155657
+ list=/tmp/point120231007155657
+ REMOVE_FS /tmp/point120231007155657
+ point_list=($1)
++ seq 0 0
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point120231007155657
++ df -T
++ grep /tmp/point120231007155657
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Sat Oct  7 15:56:57 2023 - INFO  - End to restore the test environment.
