+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Wed Sep 27 10:18:28 2023 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL aide
+ pkgs=aide
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs aide --node 1 --tempfile ''
Wed Sep 27 10:18:42 2023 - INFO  - pkgs:(aide) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Wed Sep 27 10:18:43 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Wed Sep 27 10:18:44 2023 - INFO  - Start to run test.
+ aide --init
+ grep -C 5 'initialized database'
+ grep /var/lib/aide/aide.db.new.gz
  ERROR: cannot get lock for file '/var/log/aide/aide.log': Resource temporarily unavailable
+ CHECK_RESULT 1 0 0 'Aide init datebase: failed!'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Aide init datebase: failed!'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Aide init datebase: failed!'
+ LOG_ERROR 'Aide init datebase: failed!'
+ message='Aide init datebase: failed!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Aide init datebase: failed!'
Wed Sep 27 10:18:45 2023 - ERROR - Aide init datebase: failed!
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_aide_init_database.sh line 30'
+ message='oe_test_aide_init_database.sh line 30'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_aide_init_database.sh line 30'
Wed Sep 27 10:18:45 2023 - ERROR - oe_test_aide_init_database.sh line 30
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Wed Sep 27 10:18:46 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 1
+ test 1 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Sep 27 10:18:47 2023 - ERROR - failed to execute the case.
+ exit 1
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Wed Sep 27 10:18:47 2023 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Wed Sep 27 10:18:48 2023 - WARN  - no thing to do.
+ return 0
+ rm -rf /var/lib/aide
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Wed Sep 27 10:18:48 2023 - INFO  - End to restore the test environment.
